### ISSUE TITLE
Issue loading aws sdk

### ISSUE THREAD

**Issue by coreysalzer-amazon** [coreysalzer-amazon/simplephotoboothservice#11]
Getting this issue when trying to install the aws sdk npm module:

Module parse failed: /Users/salzer/simplephotoboothservice/node_modules/aws-sdk/apis/sts-2011-06-15.paginators.json Unexpected token (2:14)
You may need an appropriate loader to handle this file type.

**Comment by ghost** [comment]
Fixed
